apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: attin-studio
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentconfig: worker
  type: ClusterIP
