apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: attin-studio
spec:
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    name: db
  type: ClusterIP
status:
  loadBalancer: {}
