apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "db"
  namespace: "attin-studio"
spec:
  accessModes:
  - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  volumeName: "pv0038"
status:
  accessModes:
  - "ReadWriteOnce"
  - "ReadWriteMany"
  - "ReadOnlyMany"
  capacity:
    storage: "100Gi"
  phase: "Bound"
